<?php
	include_once "admin_header.php" ;
	include_once '../../simantz/class/Log.inc.php';
	include_once '../class/Permission.php';
	include "../setting.php";
	include_once '../../simantz/class/SelectCtrl.inc.php';
        include_once "../../simantz/class/datepicker/class.datepicker.php";
	$ctrl=new SelectCtrl();

	error_reporting(E_ERROR | E_WARNING | E_PARSE | E_NOTICE);
	$log = new Log();
	xoops_cp_header();
	$module_id=$xoopsModule->getVar('mid');
	$tableprefix= XOOPS_DB_PREFIX . "_";
	$userid=$xoopsUser->getVar('uid');
	//$pausetime=0;
	//$tokenlife=600;
	$permission = new Permission();
	$tableuser= $tableprefix . "users";
	$tablecountry=$tableprefix."country";
	$tableclosing=$tableprefix."simbiz_closing";
	$tableaccountclass=$tableprefix."simbiz_accountclass";
	$tableaccountgroup=$tableprefix."simbiz_accountgroup";
	$tableaccounts=$tableprefix."simbiz_accounts";
	$tablebatch=$tableprefix."simbiz_batch";
	$tabledebitcreditnote=$tableprefix."simbiz_debitcreditnote";
	$tabledebitcreditnoteline=$tableprefix."simbiz_debitcreditnoteline";
	$tablebpartner=$tableprefix."bpartner";
	$tablebpartnergroup=$tableprefix."bpartnergroup";
	$tableconversion=$tableprefix."conversionrate";
	$tablecurrency=$tableprefix."currency";
	$tableorganization=$tableprefix."organization";
	$tableperiod=$tableprefix."period";
	$tablefinancialyear=$tableprefix."simbiz_financialyear";
	$tablefinancialyearline=$tableprefix."simbiz_financialyearline";
	$tabletax=$tableprefix."simbiz_tax";
	$tablegroups=$tableprefix."groups";
	$tableterms=$tableprefix."terms";
	$tabletransaction=$tableprefix."simbiz_transaction";
	$tabletranssummary=$tableprefix."simbiz_transsummary";
	$tablewindow=$tableprefix."simbiz_window";
	$tablepermission=$tableprefix."simbiz_permission";
	$tablegroups_users_link=$tableprefix."groups_users_link";
	$tablegrouppermission=$tableprefix."group_permission";
	$tablemodules=$tableprefix."modules";
	$tableconversionrate=$tableprefix."conversionrate";
	$tableusers=$tableprefix."users";
	$tablereceipt=$tableprefix."simbiz_receipt";
	$tablepaymentvoucher=$tableprefix."simbiz_paymentvoucher";
	$tablebankreconcilation=$tableprefix."simbiz_bankreconcilation";
	$tableinvoice=$tableprefix."simbiz_invoice";
	$tableinvoiceline=$tableprefix."simbiz_invoiceline";

	$defaultorganization_id=$_SESSION['defaultorganization_id'];
	?>
