<?php
$smtpserver="";
$smtpuser="";
$smtppassword="";
$senderuser="";
$tokenlife="3600";
$pausetime="1000";

$statementpapersource="1";
$prefix_je="JV";
$prefix_dcnote="DN";
$prefix_drnote="CN";
$prefix_rcpt="RC";
$prefix_pv="PV/B/";
$prefix_pvcash="PV/C/";
$prefix_spi="SI";
$prefix_spi2="PI";
$student_account="51";
$cash_account="52";
$cheque_account="50";
$student_bpartner="7";
$charges_account="51";
$payroll_account="44";
$employee_account="54";
$socso_account="46";
$epf_account="45";
$totalworkingday="365";
$totalworkinghour="8";
$sendsmsgroup="sendsmsgroup";
$orgreportheader="SIM IT SDN BHD (792899-U)";
?>
