
CREATE TABLE bpartner (
  bpartner_id int(11) NOT NULL AUTO_INCREMENT,
  bpartnergroup_id int(11) NOT NULL,
  bpartner_no varchar(10) NOT NULL,
  bpartner_name varchar(50) NOT NULL,
  isactive smallint(6) NOT NULL,
  defaultlevel int(11) NOT NULL,
  created datetime NOT NULL,
  createdby int(11) NOT NULL,
  updated datetime NOT NULL,
  updatedby int(11) NOT NULL,
  currency_id int(11) NOT NULL,
  terms_id int(11) NOT NULL,
  salescreditlimit decimal(12,2) NOT NULL,
  organization_id int(11) NOT NULL,
  bpartner_url varchar(100) NOT NULL,
  debtoraccounts_id int(11) NOT NULL,
  description text NOT NULL,
  tax_id int(11) NOT NULL,
  currentbalance decimal(12,2) NOT NULL,
  creditoraccounts_id int(11) NOT NULL,
  isdebtor smallint(1) NOT NULL,
  iscreditor smallint(1) NOT NULL,
  istransporter smallint(1) NOT NULL,
  purchasecreditlimit decimal(14,2) NOT NULL,
  enforcesalescreditlimit smallint(1) NOT NULL,
  enforcepurchasecreditlimit smallint(1) NOT NULL,
  currentsalescreditstatus decimal(14,2) NOT NULL,
  currentpurchasecreditstatus decimal(14,2) NOT NULL,
  bankaccountname varchar(50) NOT NULL,
  bankname varchar(30) NOT NULL,
  bankaccountno varchar(30) NOT NULL,
  isdealer smallint(1) NOT NULL,
  isprospect smallint(1) NOT NULL,
  employeecount int(11) NOT NULL,
  alternatename varchar(40) NOT NULL,
  companyno varchar(20) NOT NULL,
  industry_id int(11) NOT NULL,
  tooltips varchar(255) NOT NULL,
  salespricelist_id int(11) NOT NULL,
  purchasepricelist_id int(11) NOT NULL,
  employee_id int(11) NOT NULL,
  isdeleted smallint(6) NOT NULL,
  PRIMARY KEY (bpartner_id),
  UNIQUE KEY bpartner_no (bpartner_no,organization_id),
  KEY bpartnergroup_id (bpartnergroup_id),
  KEY currency_id (currency_id),
  KEY terms_id (terms_id),
  KEY organization_id (organization_id),
  KEY tax_id (tax_id),
  KEY creditoraccounts_id (creditoraccounts_id),
  KEY debtoraccounts_id (debtoraccounts_id)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=0 ;


CREATE TABLE bpartnergroup (
  bpartnergroup_id int(11) NOT NULL AUTO_INCREMENT,
  bpartnergroup_name varchar(50) NOT NULL,
  isactive smallint(6) NOT NULL,
  defaultlevel smallint(6) NOT NULL,
  created datetime NOT NULL,
  createdby int(11) NOT NULL,
  updated datetime NOT NULL,
  updatedby int(11) NOT NULL,
  organization_id int(11) NOT NULL,
  description varchar(100) NOT NULL,
  debtoraccounts_id int(11) NOT NULL,
  creditoraccounts_id int(11) NOT NULL,
  isdeleted smallint(6) NOT NULL,
  PRIMARY KEY (bpartnergroup_id),
  KEY organization_id (organization_id),
  KEY accounts_id (debtoraccounts_id),
  KEY creditoraccounts_id (creditoraccounts_id)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=0 ;


CREATE TABLE industry (
  industry_id int(11) NOT NULL AUTO_INCREMENT,
  industry_name varchar(50) NOT NULL,
  description text,
  created datetime NOT NULL,
  createdby int(11) NOT NULL,
  updated datetime NOT NULL,
  updatedby int(11) NOT NULL,
  isactive smallint(1) NOT NULL,
  defaultlevel smallint(3) NOT NULL,
  organization_id int(11) NOT NULL,
  isdeleted smallint(6) NOT NULL,
  PRIMARY KEY (industry_id),
  KEY organization_id (organization_id)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=0 ;

