<?php
$smtpserver="mail.simit.com.my";
$smtpuser="simtrain@simit.com.my";
$smtppassword="";
$smsurl="http://219.93.241.218:8080/siriesoftSMS/smsBulkERA";
$smsid="";
$smspassword="";
$smssender_name="";
$urlchecksmsbalance="http://219.93.241.218:8080/siriesoftSMS/smsRequestBalance?owner_id=$smsid&password=$smspassword";
$senderuser="";
$tokenlife="100000";
$pausetime="0";
$loglevel="0";
$logfile=XOOPS_ROOT_PATH."/modules/simantz/log.txt";
$windowsettingautosave="0";
$nitobigridthemes="vista";
$nitobicombothemes="desktopsearch";
$selectspliter="|*!*|";
$allowbrowser=array("Firefox","MSIE 8","AppleWebKit");
$sendsmsgroup="Webmasters";
$supportbrowserurl="";
$uploadpath=XOOPS_ROOT_PATH."/modules/simantz/upload/";
$uploadviewpath=XOOPS_URL."/modules/simantz/upload/";
$mandatorysign="<b style='color:red;'>*</b>";
$enforcemanager=1;
$alertmsg="";
$version="";
