<?php
$report_organizationname="SIM IT Sdn Bhd";
$report_organizationaddress="39-01, Jalan Mutiara Emas 9/3, Taman Mount Austin, 81100 Johor Bahru, Johor";
$report_organizationcontacts="Tel : 019-7725330  Fax : 07-3511757";
$smtpserver="mail.simit.com.my";
$smtpuser="kstan@simit.com.my:587";
$smtppassword="";
$smsurl="http://219.93.241.218:8080/siriesoftSMS/smsBulkERA";
$smsid="";
$smspassword="";
$smssender_name="SIMIT";
$urlchecksmsbalance="http://219.93.241.218:8080/siriesoftSMS/smsRequestBalance?owner_id=$smsid&password=$smspassword";
$senderuser="SIMIT";
$tokenlife="1000";
$pausetime="3000";
$loglevel="5";
$logfile=XOOPS_ROOT_PATH."/modules/simantz/log.txt";
$windowsettingautosave="0";
$nitobigridthemes="vista";
$nitobicombothemes="desktopsearch";
$selectspliter="|*!*|";
$allowbrowser=array("Firefox/3.6","MSIE 7","MSIE 8"," ");
$sendsmsgroup="Webmasters";
$supportbrowserurl="http://www.simit.com.my/?q=supportbrowser";
$uploadpath="../simantz/upload/";
$mandatorysign="<b style='color:red;'>*</b>";